# EXPLORACIÓN DE DATOS

In [2]:
#LIBRERIAS
import numpy as np
import pandas as pd
from datetime import datetime

In [3]:
url = "https://raw.githubusercontent.com/vicenteyanezreinoso01-spec/Proyecto-datos-an-lisis/main/Proyecto0_Manejo_de_tablas/sample_superstore.xls"

orders_df = pd.read_excel(url, sheet_name="Orders")
returns_df = pd.read_excel(url, sheet_name="Returns")
people_df = pd.read_excel(url, sheet_name="People")

In [4]:
# --- Exploracion inicial de datos orders_df ---

print("1. Primeras filas")
print(orders_df.head())

print("\n2. Info general (tipos de dato y no-nulos)")
orders_df.info()

print("\n3. Estadisticas de columnas numericas")
print(orders_df.describe())

print("\n4. Estadisticas de columnas de texto")
print(orders_df.describe(include="object"))

print("\n5. Nulos por columna")
print(orders_df.isnull().sum())

print("\n6. Filas duplicadas")
print("Cantidad de duplicados:", orders_df.duplicated().sum())

1. Primeras filas
   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

2. Info general (tipos de dato y no-nulos)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

3. Estadisticas de columnas numericas
            Row ID                     Order Date  \
count  9994.000000                           9994
mean   4997.500000  2016-04-30 00:07:12.259355648
min       1.000000            2014-01-03 00:00:00
25%    2499.250000            2015-05-23 00:00:00
50%    4997.500000            2016-06-26 00:00:00
75%    7495.750000            2017-05-14 00:00:00
max    9994.000000            2017-12-30 00:00:00
std    2885.163629                            NaN

                           Ship Date   Postal Code         Sales     Quantity  \
count                           9994   9994.000000   9994.000000  9994.000000
mean   2016-05-03 23:06:58.571142912  55190.379428    229.858001     3.789574
min              2014-01-07 00:00:00   1040.000000      0.444000     1.000000
25%              2015-05-27 00:00:00  23223.000000     17.280000     2.000000
50%              2016-06-29 00:00:00  56430.500000     54.490000     3.000000
75%              2017-05-18 00:00:00  90008.000000    209.940000     5.000000
max              2018-01-05 00:00:00  99301.000000  22638.480000    14.000000
std                              NaN  32063.693350    623.245101     2.225110

          Discount       Profit
count  9994.000000  9994.000000
mean      0.156203    28.656896
min       0.000000 -6599.978000
25%       0.000000     1.728750
50%       0.200000     8.666500
75%       0.200000    29.364000
max       0.800000  8399.976000
std       0.206452   234.260108

4. Estadisticas de columnas de texto
              Order ID       Ship Mode Customer ID  Customer Name   Segment  \
count             9994            9994        9994           9994      9994
unique            5009               4         793            793         3
top     CA-2017-100111  Standard Class    WB-21850  William Brown  Consumer
freq                14            5968          37             37      5191

              Country           City       State Region       Product ID  \
count            9994           9994        9994   9994             9994
unique              1            531          49      4             1862
top     United States  New York City  California   West  OFF-PA-10001970
freq             9994            915        2001   3203               19

               Category Sub-Category     Product Name
count              9994         9994             9994
unique                3           17             1850
top     Office Supplies      Binders  Staple envelope
freq               6026         1523               48

5. Nulos por columna
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

6. Filas duplicadas
Cantidad de duplicados: 0

In [5]:
# --- Exploracion inicial de datos returns_df ---

print("1. Primeras filas")
print(returns_df.head())

print("\n2. Info general (tipos de dato y no-nulos)")
returns_df.info()

print("\n3. Estadisticas de columnas numericas")
print(returns_df.describe())

print("\n4. Estadisticas de columnas de texto")
print(returns_df.describe(include="object"))

print("\n5. Nulos por columna")
print(returns_df.isnull().sum())

print("\n6. Filas duplicadas")
print("Cantidad de duplicados:", returns_df.duplicated().sum())

1. Primeras filas
  Returned        Order ID
0      Yes  CA-2017-153822
1      Yes  CA-2017-129707
2      Yes  CA-2014-152345
3      Yes  CA-2015-156440
4      Yes  US-2017-155999

2. Info general (tipos de dato y no-nulos)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Returned  296 non-null    object
 1   Order ID  296 non-null    object
dtypes: object(2)
memory usage: 4.8+ KB

3. Estadisticas de columnas numericas
       Returned        Order ID
count       296             296
unique        1             296
top         Yes  CA-2015-149636
freq        296               1

4. Estadisticas de columnas de texto
       Returned        Order ID
count       296             296
unique        1             296
top         Yes  CA-2015-149636
freq        296               1

5. Nulos por columna
Returned    0
Order ID    0
dtype: int64

6. Filas duplicadas
Cantidad de duplicados: 0

In [6]:
# --- Exploracion inicial de datos people_df ---

print("1. Primeras filas")
print(people_df.head())

print("\n2. Info general (tipos de dato y no-nulos)")
people_df.info()

print("\n3. Estadisticas de columnas numericas")
print(people_df.describe())

print("\n4. Estadisticas de columnas de texto")
print(people_df.describe(include="object"))

print("\n5. Nulos por columna")
print(people_df.isnull().sum())

print("\n6. Filas duplicadas")
print("Cantidad de duplicados:", people_df.duplicated().sum())

1. Primeras filas
              Person   Region
0      Anna Andreadi     West
1        Chuck Magee     East
2     Kelly Williams  Central
3  Cassandra Brandow    South

2. Info general (tipos de dato y no-nulos)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Person  4 non-null      object
 1   Region  4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

3. Estadisticas de columnas numericas
               Person Region
count               4      4
unique              4      4
top     Anna Andreadi   West
freq                1      1

4. Estadisticas de columnas de texto
               Person Region
count               4      4
unique              4      4
top     Anna Andreadi   West
freq                1      1

5. Nulos por columna
Person    0
Region    0
dtype: int64

6. Filas duplicadas
Cantidad de duplicados: 0

# MANEJO DE TABLAS CON PANDAS

#   PARTE 1 LOC

# Ejercicio 1

In [7]:
#Práctica del comando LOC.

#Ejercicio 1: usando .loc, tráeme las columnas Customer Name y Sales de los pedidos donde Sales sea mayor a 1000.
ventas_mayores1000 = orders_df.loc[
    orders_df["Sales"] > 1000,
     ["Customer Name","Sales"]]

# Ejercicio 2

In [8]:
#Ejercicio 2: con .loc, tráeme Customer Name, Sales y Region de los pedidos donde Region sea "West" y Discount sea mayor a 0.2.
pedididos_west = orders_df.loc[
    (orders_df["Discount"] > 0.2) & (orders_df["Region"] == "West"),
     ["Customer Name","Sales","Region"]]

# Ejercicio 3

In [9]:
#Ejercicio 3, uno bien del día a día — corregir datos con .loc (no solo leer, sino modificar): Los valores de Ship Mode en tu tabla vienen así: "Second Class", "Standard Class", "First Class", "Same Day". Imagina que te piden estandarizar: donde Ship Mode sea "Same Day", debes cambiarlo a "Urgente".
orders_df.loc[
    orders_df["Ship Mode"] == "Same Day",
     ["Ship Mode"]] = "Urgente"

# Ejercicio 4

In [10]:
# Ejercicio extra de .loc: dame Customer Name, Sales y Region de los pedidos donde Region sea "West" o "East"
ordenes_west_east = orders_df.loc[
    (orders_df["Region"] == "West") | (orders_df["Region"] == "East"),
     ["Customer Name","Sales","Region"]]

# Ejercicio 5

In [11]:
# Ejercicio: dame Customer Name, Sales y Region de TODOS los pedidos que NO sean de la Region "Central" (usando ~ y .loc)
pedidos_sin_Central = orders_df.loc[
     orders_df["Region"] != "Central",
              ["Customer Name","Sales","Region"]]

# Ejercicio 6

In [12]:
# Ejercicio complejo: usando .loc, dame Customer Name, Sales, Category y Region donde:
    # - Region sea "West" o "East". .isin()
    # - Y ademas Category sea Furniture. .isin()
    # - Y ademas Sales sea mayor a 300
    # Las 3 condiciones deben cumplirse a la vez

ventas_dif = orders_df.loc[
     (orders_df["Region"].isin(["West","East"])) &
         (orders_df["Category"].isin(["Furniture","Technology"])) &
             (orders_df["Sales"] > 300),
                ["Customer Name","Sales","Category","Region"]]

# PARTE 2 GROUPBY

# Ejercicio 1

In [13]:
# @title
#Práctica del comando GROUP BY.
# Ejercicio 1: dame la suma total de Sales, agrupada por Region
ventas_por_region = orders_df.groupby("Region")["Sales"].sum()

# Ejercicio 2

In [14]:
# Ejercicio 2: usando .agg(), dame en una sola tabla la suma Y el conteo de Sales, agrupado por Region (dos calculos a la vez, no uno)
ventas_region_total = orders_df.groupby("Region")["Sales"].agg(["sum", "count"])

# Ejercicio 3

In [15]:
# Ejercicio 3: ahora con nombres propios de columna, dame el promedio de Sales como "venta_promedio" y la suma de Profit como "ganancia_total", agrupado por Category
resumen_por_categoria = orders_df.groupby("Category").agg(
                           venta_promedio=("Sales", "mean"),
                              ganancia_total=("Profit", "sum"))

# Ejercicio 4

In [16]:
# Ejercicio 4: agrupado por Sub-Category, dame en una sola tabla: la cantidad de pedidos como "n_pedidos", el maximo de Sales como "venta_maxima", y el promedio de Discount como "descuento_promedio"
resumen_por_subcategoria = orders_df.groupby("Sub-Category").agg(
                                maximo_ventas=("Sales","max"),
                                promedio_descuento=("Discount","mean"),
                                n_pedidos=("Sales","count"))

# Ejercicio 5

In [17]:
# Ejercicio 5: agrupa por Region Y Category a la vez (las dos juntas, no una sola).
# Dame la suma de Sales como "venta_total" y el promedio de Profit como "ganancia_promedio".
# Extra: ordena el resultado de mayor a menor venta_total.

resumen_por_region_categoria = orders_df.groupby(["Region","Category"]).agg(
                                  ventas_totales=("Sales","sum"),
                                  ganancia_promedio=("Profit","mean"))

orden_resumen_por_region_categoria = resumen_por_region_categoria.sort_values(
              by="ventas_totales", ascending=False)

orden_resumen_por_region_categoria.head()

                        ventas_totales  ganancia_promedio
Region Category
East   Technology          264973.9810          88.714084
West   Furniture           252612.7435          16.272914
       Technology          251991.8320          73.962687
       Office Supplies     220853.2490          27.733183
East   Furniture           208291.2040           5.068496

# Ejercicio 6

In [18]:
# Ejercicio 6 (mas complejo):
#"Necesito un análisis de rentabilidad. Quiero que excluyamos los pedidos chicos (ventas de 50 dólares o menos, no son representativos). Con los pedidos que queden, arma un resumen por Región y Categoría que muestre las ventas totales y la ganancia total de cada combinación. Además, agrégale una columna de margen de ganancia (ganancia dividida en venta), para saber qué combinaciones son más rentables, no solo cuáles venden más. Ordénalo mostrando primero las combinaciones más rentables."
# 1. Primero filtra orders_df para quedarte solo con pedidos donde Sales > 50 (usa .loc)
# 2. Con ese resultado filtrado, agrupa por Region y Category
# 3. Calcula la suma de Sales como "venta_total" y la suma de Profit como "ganancia_total"
# 4. Crea una columna nueva "margen" = ganancia_total / venta_total (columna calculada DESPUES del groupby)
# 5. Ordena de mayor a menor margenn



ventas_mayores_50 = orders_df.loc[orders_df["Sales"] > 50]

resumen = ventas_mayores_50.groupby(["Region","Category"]).agg(
                                  ventas_totales=("Sales","sum"),
                                 ganancia_total=("Profit","sum"))

resumen["margen"] = resumen["ganancia_total"] / resumen["ventas_totales"]
resumen_ordenado = resumen.sort_values(by="margen", ascending=False)

resumen_ordenado.head()

                         ventas_totales  ganancia_total    margen
Region  Category
West    Office Supplies      197210.104      45126.0281  0.228822
Central Technology           167931.254      33380.4159  0.198774
East    Office Supplies      184466.782      35518.1193  0.192545
        Technology           261917.899      47173.7808  0.180109
West    Technology           249096.303      43901.0770  0.176241

# Ejercicio 7

In [19]:
#Ejercicio 7
#"El equipo comercial quiere saber si el descuento se está usausandondo de forma razonable. Para cada Segmento de cliente, necesito saber: cuántos pedidos tuvo, el descuento promedio aplicado, y la ganancia promedio. Pero además, quiero ver esto separado en dos grupos: pedidos donde SÍ hubo descuento (Discount > 0) versus donde NO hubo descuento — para comparar si dar descuento realmente afecta la ganancia."


pedidos_con_descuento = orders_df.loc[orders_df["Discount"] > 0]
pedidos_sin_descuento = orders_df.loc[orders_df["Discount"] == 0]


segmento_sin_descuento = pedidos_sin_descuento.groupby("Segment").agg(
                  n_pedido=("Segment","count"),
                  descuento_promedio=("Discount","mean"),
                  ganancia_promedio=("Profit","mean"))

segmento_con_descuento = pedidos_con_descuento.groupby("Segment").agg(
                  n_pedido=("Segment","count"),
                  descuento_promedio=("Discount","mean"),
                  ganancia_promedio=("Profit","mean"))

segmento_sin_descuento["grupo"] = "Sin descuento"
segmento_con_descuento["grupo"] = "Con descuento"

new_data = pd.concat([segmento_sin_descuento, segmento_con_descuento])
new_data.head(100)

             n_pedido  descuento_promedio  ganancia_promedio          grupo
Segment
Consumer         2461            0.000000          64.161707  Sin descuento
Corporate        1427            0.000000          71.584290  Sin descuento
Home Office       910            0.000000          66.961384  Sin descuento
Consumer         2730            0.300700          -8.711631  Con descuento
Corporate        1593            0.299969          -6.385216  Con descuento
Home Office       873            0.300493          -0.728730  Con descuento

# Ejercicio 7 (alternativa)

In [20]:
#------------OTRA FORMA DE HACERLO----------------------------
orders_df["Descuento"] = np.where(orders_df["Discount"] > 0, "Con descuento", "Sin descuento")

orden_segmento = orders_df.groupby(["Segment","Descuento"]).agg(
                n_pedidos=("Segment","count"),
                descuento_promedio=("Discount","mean"),
                ganancia_promedio=("Profit","mean"))

orden_segmento.head(100)

                           n_pedidos  descuento_promedio  ganancia_promedio
Segment     Descuento
Consumer    Con descuento       2730            0.300700          -8.711631
            Sin descuento       2461            0.000000          64.161707
Corporate   Con descuento       1593            0.299969          -6.385216
            Sin descuento       1427            0.000000          71.584290
Home Office Con descuento        873            0.300493          -0.728730
            Sin descuento        910            0.000000          66.961384

# Ejercicio 8

In [21]:
#Ejercicio 8:
#"Quiero clasificar cada pedido según su rentabilidad: 'Rentable' si Profit > 0, 'Con pérdida' si Profit <= 0 (usa np.where). Luego, agrupa por Category y esa nueva clasificación. Necesito: cantidad de pedidos, venta total, y ganancia total de cada combinación. Finalmente, quédate SOLO con las combinaciones donde hubo más de 50 pedidos con pérdida (usa .loc después de agrupar, para filtrar el resultado ya agrupado)."

orders_df["Rentabilidad"] = np.where(orders_df["Profit"] > 0 , "Rentable","Con pérdida")


agrupar_categorias = orders_df.groupby(["Category","Rentabilidad"]).agg(
              cantidad_pedidos=("Profit","count"),
              vental_total=("Sales","sum"),
              ganancia_total=("Profit","sum"))

agrupar_categorias_perdidas_sobre_50 = agrupar_categorias.loc[
               (agrupar_categorias["cantidad_pedidos"] > 50) &
               (agrupar_categorias["ganancia_total"] < 0)]

agrupar_categorias_perdidas_sobre_50.head()

                              cantidad_pedidos  vental_total  ganancia_total
Category        Rentabilidad
Furniture       Con pérdida                747   276882.8338     -60936.1090
Office Supplies Con pérdida                915   100058.2830     -56615.2585
Technology      Con pérdida                274   119452.8850     -38579.9182

# Ejercicio 9

In [22]:
# EjercicioEjercicio 9:
# "Necesito identificar los pedidos 'problematicos': aquellos con Discount mayor a 0.3
# Y ganancia negativa (Profit < 0) al mismo tiempo. Marca estos pedidos con una columna
# 'Problema' usando np.where ('Si'/'No'). Luego agrupa por Region y esa columna, mostrando
# cuantos pedidos hay y la suma de Sales perdida en cada grupo. Finalmente, quedate solo
# con las filas donde Problema sea 'Si'."

orders_df["Problematicos"] = np.where((orders_df["Discount"] > 0.3) &
                                 (orders_df["Profit"] < 0),"Si","No")

agrupacion_region_problematico = orders_df.groupby(["Region","Problematicos"]). agg(
                              cantidad_pedidos=("Problematicos","count"),
                              Ventas_total=("Sales","sum"))

agrupacion_region_problematico = agrupacion_region_problematico.reset_index()

agrupacion_region_problematico = agrupacion_region_problematico.loc[
            agrupacion_region_problematico["Problematicos"] == "Si"]


agrupacion_region_problematico.head()

    Region Problematicos  cantidad_pedidos  Ventas_total
1  Central            Si               491    62209.3588
3     East            Si               360    88301.0380
5    South            Si               171    70716.9930
7     West            Si               118    17048.6610

# Ejercicio 10

In [23]:
# Ejercicio 10:
#"Necesito un análisis de riesgo de descuento. Clasifica cada pedido en 3 niveles según el Discount: 'Bajo' (0.15 o menos), 'Medio' (más de 0.15 hasta 0.3), 'Alto' (más de 0.3) — usa np.select. Agrupa por Region y ese nivel de riesgo. Calcula: cantidad de pedidos, venta total, ganancia total, y un margen (ganancia dividida en venta, calculado después de agrupar). Finalmente, quédate solo con las combinaciones de riesgo 'Alto' que tengan margen negativo, y ordénalas de la más negativa a la menos negativa."

condiciones = [(orders_df["Discount"] <= 0.15),
                ((orders_df["Discount"] > 0.15) & (orders_df["Discount"] <= 0.3)),
                   (orders_df["Discount"] > 0.3)]

resultados = ["Bajo","Medio","Alto"]

orders_df["Risk"] = np.select(condiciones, resultados ,default="Otro")

data_regiones_risk = orders_df.groupby(["Region","Risk"]).agg(
              cantidad_pedido=("Region","count"),
              vental_total=("Sales","sum"),
              ganancia_total=("Profit","sum"))

data_regiones_risk = data_regiones_risk.reset_index()
data_regiones_risk["margen"] = data_regiones_risk["ganancia_total"] / data_regiones_risk["vental_total"]

data_regiones_risk = data_regiones_risk.loc[
    (data_regiones_risk["Risk"]=="Alto") &
    (data_regiones_risk["margen"] < 0)
]

data_regiones_risk = data_regiones_risk.sort_values(by="margen", ascending=True)

data_regiones_risk.head()

    Region  Risk  cantidad_pedido  vental_total  ganancia_total    margen
9     West  Alto              118    17048.6610     -16014.6922 -0.939352
0  Central  Alto              496    64198.8088     -45851.4202 -0.714210
3     East  Alto              381   107579.0320     -38260.1844 -0.355647
6    South  Alto              171    70716.9930     -24880.4818 -0.351832

# Ejercicio 11

In [24]:
#Enunciado — Ejercicio 11:

#"Quiero una 'Prioridad de revisión' para cada pedido, con estas 4 reglas (en este orden):

#'Critica': Profit < 0 Y Discount > 0.3
#'Alta': Profit < 0 Y Discount <= 0.3
#'Media': Profit >= 0 Y Profit < 50
#'Baja': Profit >= 50
#Usa np.select con las 4 condiciones. Luego agrupa por Category y Prioridad, calculando cantidad de pedidos y venta total. Finalmente, quédate solo con Category = 'Technology', y ordena de mayor a menor cantidad de pedidos."

condiciones = [((orders_df["Profit"] < 0) & (orders_df["Discount"] > 0.3)),
                ((orders_df["Profit"] < 0) & (orders_df["Discount"] <= 0.3)),
                ((orders_df["Profit"] >= 0) & (orders_df["Profit"] < 50)),
                ((orders_df["Profit"] >= 50))]

resultados = ["Critico","Alta","Media","Baja"]

orders_df["Prioridad"] = np.select(condiciones, resultados ,default="Otro")

data_prioridad = orders_df.groupby(["Category","Prioridad"]).agg(
              cantidad_pedido=("Profit","count"),
              vental_total=("Sales","sum"))

data_prioridad = data_prioridad.reset_index()

data_prioridad = data_prioridad.loc[data_prioridad["Category"] == "Technology"]

data_prioridad.sort_values(by="cantidad_pedido", ascending=False).head()

      Category Prioridad  cantidad_pedido  vental_total
11  Technology     Media              949    120000.129
9   Technology      Baja              627    596941.011
10  Technology   Critico              140    103072.513
8   Technology      Alta              131     16140.380

# Prueba final

In [25]:
#Enunciado — Prueba final:

#"Necesito un reporte de riesgo comercial para la gerencia. Primero, descarta los pedidos con Sales de 20 dólares o menos (son ruido, no aportan). Con lo que quede, clasifica cada pedido en un 'Perfil', evaluado en este orden:

#'Descuento excesivo': Discount mayor a 0.4
#'Perdida sin descuento alto': Profit menor a 0 Y Discount de 0.4 o menos
#'Alto volumen bajo margen': Quantity de 6 o más Y Profit menor a 100
#Todo lo demás: 'Normal'

#Agrupa por Region, Category y Perfil (las tres a la vez). Necesito, por cada combinación: cantidad de pedidos, venta total y ganancia total. Agrega una columna de margen (ganancia entre venta).

#Quédate solo con combinaciones que tengan más de 15 pedidos y que NO sean 'Normal' — no me interesa lo normal, quiero ver los perfiles de riesgo. Ordena mostrando primero el peor margen, y déjame solo el top 10 más crítico."

riesgo_df = orders_df.loc[orders_df["Sales"] > 20].copy()

condiciones = [(riesgo_df["Discount"] > 0.40),
               ((riesgo_df["Discount"] <= 0.40) & (riesgo_df["Profit"] < 0)),
                ((riesgo_df["Quantity"] >= 6) & (riesgo_df["Profit"] < 100))]

clasificacion = ["Descuento excesivo", "Perdida sin descuento alto",
                 "Alto volumen bajo margen"]

riesgo_df["Perfil"] = np.select(condiciones, clasificacion, default="Normal")

riesgo_df = riesgo_df.groupby(["Region","Category","Perfil"]).agg(
              cantidad_pedido=("Profit","count"),
              vental_total=("Sales","sum"),
              ganancia_total=("Profit","sum"))

riesgo_df = riesgo_df.reset_index()

riesgo_df["margen"] = riesgo_df["ganancia_total"] / riesgo_df["vental_total"]

riesgo_df = riesgo_df.loc[(riesgo_df["cantidad_pedido"] > 15) & (riesgo_df["Perfil"] !="Normal")]

riesgo_df.nsmallest(10, "margen")

,Region,Category,Perfil,cantidad_pedido,vental_total,ganancia_total,margen
5,Central,Office Supplies,Descuento excesivo,83,15540.402,-28041.0166,-1.804395
36,West,Furniture,Descuento excesivo,33,9583.722,-8200.5820,-0.855678
1,Central,Furniture,Descuento excesivo,95,12603.110,-9882.9094,-0.784164
40,West,Office Supplies,Descuento excesivo,25,2560.920,-1917.9766,-0.748940
28,South,Office Supplies,Descuento excesivo,45,10699.272,-7883.1350,-0.736792
16,East,Office Supplies,Descuento excesivo,49,7261.821,-5291.5721,-0.728684
12,East,Furniture,Descuento excesivo,18,7308.460,-4255.8117,-0.582313
26,South,Furniture,Perdida sin descuento alto,47,25257.064,-7428.9135,-0.294132
22,East,Technology,Perdida sin descuento alto,114,34945.030,-6986.6651,-0.199933
18,East,Office Supplies,Perdida sin descuento alto,52,19362.584,-3798.0279,-0.196153

In [26]:
orders_df
returns_df
people_df

              Person   Region
0      Anna Andreadi     West
1        Chuck Magee     East
2     Kelly Williams  Central
3  Cassandra Brandow    South

# PARTE 3 MERGE

#Ejercicio 1:
"El equipo de logística quiere saber qué pedidos fueron devueltos. Necesito que unas la tabla de Orders con la de Returns, usando el número de pedido como referencia. Es importante que NO pierdas ningún pedido en el proceso — incluso los que nunca fueron devueltos deben seguir apareciendo en el resultado, aunque no tengan información de devolución."

In [27]:
ordern_return = orders_df.merge(returns_df, how="left", left_on="Order ID", right_on="Order ID")
ordern_return.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Descuento,Rentabilidad,Problematicos,Risk,Prioridad,Returned
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,Sin descuento,Rentable,No,Bajo,Media,NaN
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,Sin descuento,Rentable,No,Bajo,Baja,NaN
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,Sin descuento,Rentable,No,Bajo,Media,NaN
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,Con descuento,Con pérdida,Si,Alto,Critico,NaN
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,Con descuento,Rentable,No,Medio,Media,NaN

# Ejercicio 2:
"Esos NaN en la columna Returned no significan que falte informacion, significan que el pedido nunca fue devuelto. Reemplaza los valores nulos de Returned por 'No', y confirma que ya no queden nulos en esa columna."

In [28]:
ordern_return["Returned"] = ordern_return["Returned"].fillna("No")
ordern_return.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Descuento,Rentabilidad,Problematicos,Risk,Prioridad,Returned
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,Sin descuento,Rentable,No,Bajo,Media,No
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,Sin descuento,Rentable,No,Bajo,Baja,No
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,Sin descuento,Rentable,No,Bajo,Media,No
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,Con descuento,Con pérdida,Si,Alto,Critico,No
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,Con descuento,Rentable,No,Medio,Media,No

# Ejercicio 3:
"Ahora necesito saber qué gerente (Person) es responsable de cada pedido, segun la Region a la que pertenece. Une la tabla que ya tienes (ordern_return, que ya incluye Orders + Returns) con people_df, usando 'Region' como columna clave. Usa how='left' otra vez, para no perder ningun pedido."

In [29]:
people_df
ordern_return_people = ordern_return.merge(people_df, "left", "Region")
ordern_return_people

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,Descuento,Rentabilidad,Problematicos,Risk,Prioridad,Returned,Person
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.00,41.9136,Sin descuento,Rentable,No,Bajo,Media,No,Cassandra Brandow
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.00,219.5820,Sin descuento,Rentable,No,Bajo,Baja,No,Cassandra Brandow
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.00,6.8714,Sin descuento,Rentable,No,Bajo,Media,No,Anna Andreadi
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,5,0.45,-383.0310,Con descuento,Con pérdida,Si,Alto,Critico,No,Cassandra Brandow
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2,0.20,2.5164,Con descuento,Rentable,No,Medio,Media,No,Cassandra Brandow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,3,0.20,4.1028,Con descuento,Rentable,No,Medio,Media,No,Cassandra Brandow
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,2,0.00,15.6332,Sin descuento,Rentable,No,Bajo,Media,Yes,Anna Andreadi
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,2,0.20,19.3932,Con descuento,Rentable,No,Medio,Media,Yes,Anna Andreadi
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,4,0.00,13.3200,Sin descuento,Rentable,No,Bajo,Media,Yes,Anna Andreadi
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,2,0.00,72.9480,Sin descuento,Rentable,No,Bajo,Baja,No,Anna Andreadi

In [30]:
profitmean_pedidos = ordern_return_people.groupby("Returned").agg(
                                        cantidad_pedidos = ("Returned","count"),
                                        promedio_profit = ("Profit","mean"))
profitmean_pedidos

          cantidad_pedidos  promedio_profit
Returned
No                    9194        28.623522
Yes                    800        29.040452

# PARTE  4 PIVOT TABLE

# Ejercicio 1:
"Necesito ver las ventas totales, con Region en las filas y Category en las columnas, para poder comparar rapido de un vistazo qué región vende más en cada categoría. Usa pivot_table con orders_df."

In [31]:
pd.pivot_table(orders_df,
               index="Region",
               columns="Category",
               values="Sales",
               aggfunc="sum")

Category    Furniture  Office Supplies  Technology
Region
Central   163797.1638       167026.415  170416.312
East      208291.2040       205516.055  264973.981
South     117298.6840       125651.313  148771.908
West      252612.7435       220853.249  251991.832

# Ejercicio 2:
"Ahora quiero lo mismo pero con dos metricas a la vez: ademas de la suma de Sales, necesito tambien el promedio de Profit, con Region en filas y Category en columnas. Usa pivot_table con una lista en values y una lista en aggfunc."

In [32]:
a = pd.pivot_table(orders_df, index="Region", columns=("Category"),values=("Sales","Profit"), aggfunc={"Sales": "sum", "Profit": "mean"})

# Ejercicio 3:
"En la tabla de arriba, si una region no tuvo ninguna venta en alguna categoria, quiero que se muestre como 0 en vez de vacio (NaN). Ademas, quiero una fila y columna extra con el total general de cada region y cada categoria."

In [33]:
pd.pivot_table(
  orders_df, index="Region",
  columns="Category",
  values="Sales",
  aggfunc="sum",
  fill_value=0,
  margins=True)

Category    Furniture  Office Supplies  Technology           All
Region
Central   163797.1638       167026.415  170416.312  5.012399e+05
East      208291.2040       205516.055  264973.981  6.787812e+05
South     117298.6840       125651.313  148771.908  3.917219e+05
West      252612.7435       220853.249  251991.832  7.254578e+05
All       741999.7953       719047.032  836154.033  2.297201e+06

# Ejercicio 4:
"Necesito revisar la rentabilidad, pero solo de los pedidos que realmente importan: descarta los que tuvieron Sales de 100 o menos (ya sabes hacer esto con .loc). Con lo que quede, quiero una tabla cruzada donde las filas sean Region Y Segment a la vez (las dos juntas, como una jerarquia), las columnas sean Category, y los valores sean el promedio de Profit. Rellena los huecos con 0, y agrega los totales generales."1

In [34]:
orders_mayor_100 = orders_df.loc[orders_df["Sales"] >= 100 ]
pd.pivot_table(
      orders_mayor_100, index=("Region","Segment"),
      columns="Category",
      values="Profit",
      aggfunc="mean",
      fill_value=0,
      margins=True)

Category             Furniture  Office Supplies  Technology         All
Region  Segment
Central Consumer    -17.496642        20.491218   68.389840   21.792451
        Corporate    36.444817        12.392707  210.917673   86.691964
        Home Office -16.928513       105.622947  128.131267   74.962634
East    Consumer      6.209355        79.591056  112.015231   63.600296
        Corporate    -2.608148        94.524050   88.836092   58.362436
        Home Office   5.071221       106.234744  286.256710  134.332852
South   Consumer     34.112560        62.305481  133.242712   72.505743
        Corporate    12.684024        96.782868  114.403266   75.263233
        Home Office  37.166273        48.741214   15.648503   34.213797
West    Consumer     13.919298        88.095031  127.156100   73.625078
        Corporate    25.998263       113.686937   96.374313   76.281722
        Home Office  38.100195        95.970286   60.811499   63.966521
All                  12.078401        77.084337  117.705406   67.174902

# Ejercicio 5

De: Gerencia Comercial
Para: Analista de Datos

Hola, necesito un análisis rápido para la reunión de la próxima semana.

Quiero entender cómo se ha comportado la rentabilidad de nuestras categorías de producto a lo largo de los años que tenemos registrados. No me sirve solo ver cuánta plata ganamos en dólares — eso ya lo sé, y además una categoría grande siempre va a ganar más en términos absolutos aunque no sea la más eficiente. Lo que necesito es saber qué tan rentable es cada categoría en proporción a lo que vende, y cómo ha cambiado eso año a año.

Al final quiero poder responder, con un solo vistazo a una tabla, dos preguntas: ¿qué categoría es la más rentable proporcionalmente en cada año?, y ¿hay alguna categoría que se esté deteriorando con el tiempo?

Prepárame algo entendible, no me mandes el dataset crudo.

Gracias.

In [35]:
#OPCION A "Margin = orders_df["Profit"] / orders_df["Sales"]"
orders_df["Rendimiento"] = orders_df["Profit"] / orders_df["Sales"]
orders_df["Year"] = pd.DatetimeIndex(orders_df["Order Date"]).year
orders_df.pivot_table(
              index = "Category",
              columns = "Year",
              values = "Rendimiento",
              aggfunc = "mean",
              fill_value = 0,
              margins = True)

Year                 2014      2015      2016      2017       All
Category
Furniture        0.035310  0.041470  0.039468  0.038584  0.038784
Office Supplies  0.134360  0.128772  0.160883  0.128125  0.138030
Technology       0.160607  0.167664  0.134296  0.162107  0.156138
All              0.118112  0.117567  0.129789  0.115981  0.120314

In [36]:
# OPCION B dejar que el pivot sume Profit y sume Sales por separado
# (values=["Profit","Sales"], aggfunc="sum"),
# y recién ahí, con los totales ya agregados, dividir una columna por la otra —
# esto te da el margen del grupo como un todo (ganancia total del grupo sobre venta total del grupo).

tabla_opcionb = pd.pivot_table(orders_df,
              index="Category",
              columns="Year",
              values=["Sales", "Profit"],
              aggfunc="sum",
              fill_value=0,
              margins=True)

margenes_opcionb = tabla_opcionb["Profit"] / tabla_opcionb["Sales"]
margenes_opcionb

Year                 2014      2015      2016      2017       All
Category
Furniture        0.034720  0.017683  0.034992  0.014014  0.024867
Office Supplies  0.148860  0.182897  0.190612  0.161467  0.170352
Technology       0.122621  0.205822  0.175708  0.186524  0.173957
All              0.102311  0.130955  0.134265  0.127438  0.124672

In [37]:
#Vemos la evolución año tras año de los margenes, (año n - año(n-1))
años = margenes_opcionb[[2014, 2015, 2016, 2017]]
variacion_anual = años.diff(axis=1)
variacion_anual

Year             2014      2015      2016      2017
Category
Furniture         NaN -0.017037  0.017309 -0.020978
Office Supplies   NaN  0.034037  0.007716 -0.029145
Technology        NaN  0.083201 -0.030114  0.010816
All               NaN  0.028644  0.003310 -0.006828

In [38]:
#Margenes ultimo - primer periodo (queremos ver el punto de partida vs el ultimo punto)
margenes_opcionb["diferencia_primer_ultimo_periodo"] = margenes_opcionb[2017] - margenes_opcionb[2014]
margenes_opcionb["diferencia_primer_ultimo_periodo"]

Category
Furniture         -0.020706
Office Supplies    0.012607
Technology         0.063903
All                0.025126
Name: diferencia_primer_ultimo_periodo, dtype: float64

# Ejercicio 6:
De: Gerencia de Logística
Para: Analista de Datos

Hola, necesito otra cosa para la reunión.

Quiero saber qué tan rápido estamos despachando los pedidos. Necesito el promedio de días que pasan entre que se genera el pedido y se despacha, separado por Región y por el modo de envío que eligió el cliente (Ship Mode).

Me interesan dos cosas puntuales: si alguna región tarda sistemáticamente más que las demás sin importar el modo de envío elegido, y si el envío "Same Day" realmente está cumpliendo (0 días de diferencia) o hay excepciones que deberíamos revisar.

Gracias.

In [39]:
orders_df["Velocidad_pedidos"] = (orders_df["Ship Date"] - orders_df["Order Date"]).dt.days

pd.pivot_table(
          orders_df,
          index = "Region",
          columns = "Ship Mode",
          values = "Velocidad_pedidos",
          aggfunc = "mean",
          fill_value = 0,
          margins = True)

Ship Mode  First Class  Second Class  Standard Class   Urgente       All
Region
Central       2.317726      3.331183        4.990271  0.033333  4.058115
East          2.224490      3.266038        4.967723  0.000000  3.908708
South         2.111111      3.194529        4.995893  0.012048  3.958025
West          2.097087      3.167472        5.058980  0.102703  3.929753
All           2.182705      3.238046        5.006535  0.044199  3.958175

# Ejercicio 7 (dificil - cierre de pivot_table):
De: Direccion Financiera
Para: Analista de Datos

Hola, necesito algo mas fino que el reporte de margenes que ya vimos.

Quiero evaluar el impacto real del descuento en nuestra rentabilidad estructural. Para eso, considera UNICAMENTE los pedidos donde se aplico algun descuento (los que no tuvieron descuento no nos sirven para esta pregunta, distorsionarian la comparacion).

Con esos pedidos, necesito el margen real (no el promedio ingenuo de porcentajes, el que ya sabes calcular bien) cruzando Categoria y Segmento de cliente contra cada año.

Quiero que me digas dos cosas concretas: cual es la combinacion de Categoria y Segmento con el margen MAS BAJO en 2017 (el año mas reciente que tenemos), y cuanto ha cambiado esa misma combinacion especifica desde 2014 hasta 2017 (en puntos porcentuales, no en dolares).

Gracias.

In [40]:
orders_con_descuento = orders_df.loc[orders_df["Discount"] > 0]


margenes_categoria_segment = pd.pivot_table(
           orders_con_descuento,
           index = ("Segment","Category"),
           columns = "Year",
           values = ["Sales", "Profit"],
           aggfunc= "sum",
           fill_value=0,
           margins = True)

margenes_categoria_segment = margenes_categoria_segment["Profit"] / margenes_categoria_segment["Sales"]
print(margenes_categoria_segment)
print("")
print("")
print("")

diferencia = (margenes_categoria_segment[2017] - margenes_categoria_segment[2014]).loc[("Home Office","Office Supplies")]

diferencia

Year                             2014      2015      2016      2017       All
Segment     Category
Consumer    Furniture       -0.049509 -0.148694 -0.062703 -0.075582 -0.083099
            Office Supplies -0.118001 -0.068687 -0.008061 -0.049573 -0.059344
            Technology       0.022054  0.072222 -0.016219  0.068333  0.032803
Corporate   Furniture       -0.096603 -0.028629 -0.072032 -0.118864 -0.080532
            Office Supplies -0.025245 -0.011090  0.007725  0.016063  0.002429
            Technology      -0.000962  0.049713  0.031993 -0.012263  0.010301
Home Office Furniture       -0.008177 -0.030239 -0.155889 -0.101350 -0.078912
            Office Supplies  0.043434 -0.004975  0.116220 -0.126284  0.018319
            Technology      -0.003264  0.116718  0.008214  0.084858  0.043754
All                         -0.033693 -0.029720 -0.024220 -0.027884 -0.028604

np.float64(-0.1697178793034939)

# PARTE 5: ILOC

### Ejercicio 1 — iloc básico

1. Usando `.iloc`, trae las primeras 5 filas de `orders_df`, con TODAS las columnas.
2. Ahora, usando `.iloc`, trae solamente las columnas en las posiciones 0, 1 y 2 (sin importar cómo se llamen), para todas las filas.
3. Combina ambos: trae las filas en posición 10 a 15, y solo las columnas en posición 4 a 7.

Antes de correr cada uno, predice: ¿cuántas filas y columnas debería tener el resultado exacto de cada punto? Cuéntame tu predicción antes de ejecutar.

In [41]:
#1. Punto 1  Usando .iloc, trae las primeras 5 filas de orders_df, con TODAS las columnas.
prueba_1 = orders_df.iloc[0:5]
prueba_1
#2. Punto 2 trae solamente las columnas en las posiciones 0, 1 y 2 (sin importar cómo se llamen), para todas las filas.
prueba_2 = orders_df.iloc[:, 0:3]
prueba_2
#3.
prueba_3 = orders_df.iloc[10:16, 4:8]
prueba_3

         Ship Mode Customer ID    Customer Name      Segment
10  Standard Class    BH-11710  Brosina Hoffman     Consumer
11  Standard Class    BH-11710  Brosina Hoffman     Consumer
12  Standard Class    AA-10480     Andrew Allen     Consumer
13  Standard Class    IM-15070     Irene Maddox     Consumer
14  Standard Class    HP-14815    Harold Pawlan  Home Office
15  Standard Class    HP-14815    Harold Pawlan  Home Office

### Ejercicio 2 — iloc, cierre rápido

1. Trae las últimas 3 filas de `orders_df`, todas las columnas (usa índice negativo).
2. Trae las filas en las posiciones 0, 100 y 500 (una lista, no un rango) — solo la columna `Customer Name`.
3. Usando `.iat[]`, trae el valor puntual de la fila en posición 0 y la columna en posición 8 (un solo número/dato, no una tabla).

In [42]:
#1.
ultimas_filas = orders_df.iloc[-3:]
ultimas_filas
#2.
posicion = orders_df.iloc[[0,100,500],6]
posicion
#3.
pos = orders_df.iat[0, 8]
pos

print(ultimas_filas)
print(posicion)
print(pos)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID Customer Name   Segment        Country         City  ...  \
9991    DB-13060   Dave Brooks  Consumer  United States   Costa Mesa  ...
9992    DB-13060   Dave Brooks  Consumer  United States   Costa Mesa  ...
9993    CC-12220  Chris Cortes  Consumer  United States  Westminster  ...

     Discount   Profit      Descuento Rentabilidad Problematicos   Risk  \
9991      0.2  19.3932  Con descuento     Rentable            No  Medio
9992      0.0  13.3200  Sin descuento     Rentable            No   Bajo
9993      0.0  72.9480  Sin descuento     Rentable            No   Bajo

     Prioridad  Rendimiento  Year  Velocidad_pedidos
9991     Media        0.075  2017                  5
9992     Media        0.450  2017                  5
9993      Baja        0.300  2017                  5

[3 rows x 29 columns]
0          Claire Gute
100       Rick Bensley
500    Maribeth Yedwab
Name: Customer Name, dtype: object
United States

# PARTE 6: GROUPBY + TRANSFORM

### Ejercicio — groupby().transform()

1. Crea una columna nueva llamada `Total_Categoria` en `orders_df`, usando `.transform("sum")`,
   que muestre para cada pedido la venta TOTAL de su categoría (agrupando por `Category`,
   sobre la columna `Sales`).

2. Verificación: filtra 2-3 filas cualquiera que pertenezcan a la misma `Category` y confirma
   que el valor de `Total_Categoria` es idéntico entre ellas.

3. Usando esa columna, crea `Porcentaje_del_total_categoria` = `Sales / Total_Categoria`.
   Esto te dice qué proporción de la venta total de su categoría representa ese pedido puntual.

In [43]:
orders_df["Total_Categoria"] = orders_df.groupby("Category")["Sales"].transform("sum")

verificacion = orders_df.loc[orders_df["Category"] == "Technology"]

orders_df["Porcentaje_del_total_categoria"] = (orders_df["Sales"] / orders_df["Total_Categoria"])*100
orders_df["Porcentaje_del_total_categoria"]

0       0.035305
1       0.098644
2       0.002033
3       0.129054
4       0.003111
          ...
9989    0.003403
9990    0.012394
9991    0.030924
9992    0.004117
9993    0.033817
Name: Porcentaje_del_total_categoria, Length: 9994, dtype: float64

# PARTE 7: .FILTER()

### Ejercicio 1 — groupby().filter()
Sintaxis: df.groupby("columna").filter(lambda x: condición_sobre_el_grupo)

1. Quédate solo con las filas de Sub-Category cuyo total de Sales (sumado) sea mayor a 200,000.
   Es decir: descarta grupos ENTEROS de Sub-Category que no lleguen a ese umbral — no filas
   individuales de pedidos chicos, sino subcategorías completas que en conjunto no vendan lo
   suficiente.

2. Verifica: ¿cuántas Sub-Category distintas quedaron después del filtro, de las 17 originales?

In [44]:
sub_Category = orders_df.groupby("Sub-Category").filter(lambda x: x["Sales"].sum() >200000 )
sub_Category["Sub-Category"].nunique()

5

### Ejercicio 2 — groupby().filter(), combinando condiciones

Esta vez la condición no es una sola — igual que en `.loc`, dentro del `lambda` puedes combinar
más de una condición con `&` (recuerda encerrar cada condición entre paréntesis).

1. Quédate solo con los `Customer ID` (clientes) que cumplan LAS DOS condiciones a la vez:
   - Hicieron más de 10 pedidos en total
   - Su promedio de `Profit` es mayor a 0 (o sea, en promedio les fue rentable, no a pérdida)

2. Verifica: ¿cuántos `Customer ID` distintos quedaron, de los 793 originales?

In [45]:
clientes_mayor_10_pedidos = orders_df.groupby(
    "Customer ID").filter(lambda x: (x["Customer ID"].count() > 10) & (x["Profit"].sum() > 0))

clientes_mayor_10_pedidos["Customer ID"].nunique()

387

### Ejercicio 3 — filter() más complejo

De: Gerencia de Producto
Para: Analista de Datos

Necesito identificar qué Sub-Category realmente vale la pena seguir empujando comercialmente.
Quiero quedarme SOLO con los pedidos que pertenezcan a una Sub-Category que cumpla, al mismo
tiempo, las tres condiciones siguientes:

- Vendió en total más de 300 pedidos (volumen real, no un producto de nicho)
- Su ganancia total sumada es positiva (no es una categoría que en conjunto pierde plata)
- Su descuento promedio no supera el 0.2 (no depende de rebajar precio para vender)

Dame la tabla resultante (detalle fila por fila, sin agrupar) y dime cuántas Sub-Category
distintas, de las 17 originales, cumplen las tres condiciones a la vez.

In [46]:
solicitud_gerencia_producto = orders_df.groupby("Sub-Category").filter(lambda x: (x["Sales"].count() > 300 ) &
                                         (x["Profit"].sum() > 0) & (x["Discount"].mean() <= 0.2))

solicitud_gerencia_producto["Sub-Category"].nunique()

9

### Ejercicio 4

De: Dirección Comercial
Para: Analista de Datos

Necesito armar una lista de candidatos para un programa de fidelización de clientes.

Quiero quedarme únicamente con los pedidos de clientes que cumplan, ambas cosas a la vez:
- Han comprado en más de una Category distinta (no me interesan los clientes de un solo rubro)
- Su gasto total acumulado (Sales) supera los $5,000

De los pedidos que sobrevivan ese filtro, necesito además que cada pedido individual muestre
qué porcentaje representa sobre el gasto TOTAL de ese cliente específico — quiero poder ver,
de un vistazo, si el gasto de un cliente está concentrado en pocos pedidos grandes o repartido
parejo entre muchos.

No te digo cómo hacerlo. Resuélvelo.

In [47]:
lista_clientes_fidelizacion = orders_df.groupby("Customer ID").filter(
    lambda z: (z["Category"].nunique() > 1) & (z["Sales"].sum() > 5000))

lista_clientes_fidelizacion["total_cliente"] = lista_clientes_fidelizacion.groupby("Customer ID")["Sales"].transform("sum")
lista_clientes_fidelizacion["participacion_pedido"] = (lista_clientes_fidelizacion["Sales"] / lista_clientes_fidelizacion["total_cliente"])*100

lista_clientes_fidelizacion

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Problematicos,Risk,Prioridad,Rendimiento,Year,Velocidad_pedidos,Total_Categoria,Porcentaje_del_total_categoria,total_cliente,participacion_pedido
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,No,Bajo,Media,0.290000,2014,5,741999.7953,0.006585,6255.3510,0.781091
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,No,Bajo,Media,0.270000,2014,5,719047.0320,0.001012,6255.3510,0.116380
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,No,Medio,Baja,0.100000,2014,5,836154.0330,0.108491,6255.3510,14.502016
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,No,Medio,Media,0.312500,2014,5,719047.0320,0.002573,6255.3510,0.295811
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,No,Bajo,Media,0.300000,2014,5,719047.0320,0.015979,6255.3510,1.836827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9950,9951,CA-2017-121559,2017-06-01,2017-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,No,Bajo,Media,0.370000,2017,2,836154.0330,0.004771,9300.2540,0.428913
9951,9952,CA-2017-121559,2017-06-01,2017-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,No,Bajo,Media,0.500000,2017,2,719047.0320,0.002417,9300.2540,0.186877
9961,9962,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,No,Medio,Media,0.362500,2015,3,719047.0320,0.009121,6339.5576,1.034520
9962,9963,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,Si,Alto,Critico,-0.176471,2015,3,741999.7953,0.051680,6339.5576,6.048775
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,No,Medio,Media,0.162500,2014,2,741999.7953,0.003403,9133.9900,0.276418

### Encargo — Ejercicio 5: Productos inconsistentes

De: Control de Calidad Comercial
Para: Analista de Datos

Necesito detectar productos que son "apuestas riesgosas" — no los malos de plano, sino los
inconsistentes: que en general dan ganancia, pero que en algún momento fallaron feo.

Quiero quedarme con los `Product ID` que cumplan las TRES condiciones a la vez:
- Se vendieron en al menos 5 pedidos distintos (no quiero productos anecdóticos)
- Su ganancia PROMEDIO es positiva (en general, el producto funciona)
- Pero tuvieron AL MENOS UN pedido con ganancia negativa (no siempre funcionó)

Con los pedidos de esos productos que sobrevivan el filtro, agrega una columna que muestre,
para cada pedido individual, qué tan lejos está su `Profit` del `Profit` PROMEDIO de su propio
producto — la diferencia en dólares, no en porcentaje (puede salir positiva o negativa, eso
está bien, así veo si ese pedido puntual estuvo mejor o peor que el promedio habitual del producto).

No te digo qué herramientas usar.

In [48]:
productos_calidad = orders_df.groupby("Product ID").filter(lambda x: (x["Order ID"].nunique() >= 5) &
                                                           (x["Profit"].mean() > 0) &
                                                           (x["Profit"].min() < 0))

productos_calidad["mean_product"] = productos_calidad.groupby("Product ID")["Profit"].transform("mean")

productos_calidad["distance_profit_group"] = productos_calidad["Profit"] - productos_calidad["mean_product"]

productos_calidad

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Problematicos,Risk,Prioridad,Rendimiento,Year,Velocidad_pedidos,Total_Categoria,Porcentaje_del_total_categoria,mean_product,distance_profit_group
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,No,Medio,Media,0.312500,2014,5,719047.0320,0.002573,6.669150,-0.886650
13,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,No,Medio,Baja,0.325000,2016,5,719047.0320,0.056738,77.062133,55.530067
14,15,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Si,Alto,Critico,-1.800000,2015,4,719047.0320,0.009570,38.120740,-161.978740
15,16,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Si,Alto,Critico,-1.500000,2015,4,719047.0320,0.000354,1.431000,-5.247000
23,24,US-2017-156909,2017-07-16,2017-07-18,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,No,Medio,Alta,-0.014286,2017,2,741999.7953,0.009619,10.997114,-12.016714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9979,9980,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,No,Medio,Baja,0.350000,2016,4,719047.0320,0.060841,24.973800,128.141400
9983,9984,US-2016-157728,2016-09-22,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,No,Bajo,Media,0.280000,2016,6,836154.0330,0.011718,25.801400,1.633000
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,No,Bajo,Media,0.170000,2017,5,741999.7953,0.012394,17.800829,-2.167629
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,No,Medio,Media,0.075000,2017,5,836154.0330,0.030924,82.190229,-62.797029
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,No,Bajo,Baja,0.300000,2017,5,719047.0320,0.033817,57.316286,15.631714

### Encargo — Cierre de filter: Clientes de alto riesgo

De: Riesgo Crediticio
Para: Analista de Datos

Necesito una lista de clientes considerados "alto riesgo" para revisión de sus condiciones
de crédito. Un cliente califica como alto riesgo si cumple **cualquiera** de estos dos
escenarios (no hace falta que cumpla ambos, con uno solo ya califica):

**Escenario A** — las tres condiciones a la vez:
- Ha hecho al menos 8 pedidos
- Su descuento promedio supera 0.2
- Su ganancia total (sumada) es negativa

**Escenario B** — las dos condiciones a la vez:
- Su pedido de mayor venta individual (el máximo de Sales que ha hecho) superó los $5,000
- Y tuvo al menos un pedido con pérdida (Profit negativo)

Con los pedidos de todos los clientes que califiquen por cualquiera de los dos escenarios,
clasifica cada pedido individual como "Pérdida" o "Ganancia" según su Profit.

Finalmente, dame un resumen: para cada cliente calificado, cuántos de sus pedidos cayeron
en "Pérdida" y cuántos en "Ganancia".

No te digo qué herramientas usar, ni en qué orden.

In [49]:
#SOLUCIÓN PROPIA
Customers_risk_condition_A = orders_df.groupby("Customer ID").filter(
    lambda x: (x["Order ID"].nunique() > 7) &
              (x["Discount"].mean() > 0.2) &
              (x["Profit"].sum() < 0))

Customers_risk_condition_B = orders_df.groupby("Customer ID").filter(
    lambda x: (x["Sales"].max() > 5000) &
    (x["Profit"].min() < 0))

customer_risk = pd.concat([Customers_risk_condition_A, Customers_risk_condition_B], ignore_index=True).drop_duplicates()

customer_risk["Clasificacion_profit"] = np.where(customer_risk["Profit"] > 0,"Ganancia", "Perdida" )


resumen = customer_risk.pivot_table (
          index= "Customer ID",
          columns= "Clasificacion_profit",
          values="Sales",
          aggfunc="count",
          margins=True,
          margins_name="Total")

resumen

Clasificacion_profit  Ganancia  Perdida  Total
Customer ID
AB-10105                    13        7     20
BM-11140                    11        5     16
CC-12370                     7        4     11
CM-12385                     9        1     10
CP-12340                     8        7     15
CS-11950                    14        8     22
CS-12400                     7        7     14
DC-12850                    12        6     18
DR-12940                     9        4     13
EA-14035                    15       10     25
GH-14410                    10        7     17
GT-14635                     4        2      6
JA-15970                    18        6     24
JW-15220                    12        2     14
KL-16555                    12       10     22
KL-16645                    22        7     29
KN-16390                     9        8     17
LB-16795                    16        8     24
LC-16870                    21        9     30
MC-18100                     8       11     19
MK-17905                    12        5     17
MM-18055                    14        5     19
MY-18295                    14        7     21
NS-18640                    20        6     26
RB-19360                    17        1     18
RB-19795                    11        7     18
SC-20095                    20        2     22
SE-20110                    16        3     19
SH-20395                     9        6     15
SM-20320                    10        5     15
SP-20620                    16        8     24
TA-21385                     9        1     10
TB-21520                    14        6     20
TC-20980                    11        1     12
TS-21370                    12        3     15
ZC-21910                    18       13     31
Total                      460      208    668

In [50]:
#SOLUCION B
clientes_riesgo = orders_df.groupby("Customer ID").filter(
    lambda x: (
        (x["Order ID"].nunique() >= 8) &
        (x["Discount"].mean() > 0.2) &
        (x["Profit"].sum() < 0)
    ) | (
        (x["Sales"].max() > 5000) &
        (x["Profit"].min() < 0)))

clientes_riesgo["Clasificacion_profit"] = np.where(
    clientes_riesgo["Profit"] > 0, "Ganancia", "Pérdida")

resumen = clientes_riesgo.pivot_table(
    index="Customer ID",
    columns="Clasificacion_profit",
    values="Sales",
    aggfunc="count",
    fill_value=0,
    margins=True,
    margins_name="Total")

resumen

Clasificacion_profit  Ganancia  Pérdida  Total
Customer ID
AB-10105                    13        7     20
BM-11140                    11        5     16
CC-12370                     7        4     11
CM-12385                     9        1     10
CP-12340                     8        7     15
CS-11950                    14        8     22
CS-12400                     7        7     14
DC-12850                    12        6     18
DR-12940                     9        4     13
EA-14035                    15       10     25
GH-14410                    10        7     17
GT-14635                     4        2      6
JA-15970                    18        6     24
JW-15220                    12        2     14
KL-16555                    12       10     22
KL-16645                    22        7     29
KN-16390                     9        8     17
LB-16795                    16        8     24
LC-16870                    21        9     30
MC-18100                     8       11     19
MK-17905                    12        5     17
MM-18055                    14        5     19
MY-18295                    14        7     21
NS-18640                    20        6     26
RB-19360                    17        1     18
RB-19795                    11        7     18
SC-20095                    20        2     22
SE-20110                    16        3     19
SH-20395                     9        6     15
SM-20320                    10        5     15
SP-20620                    16        8     24
TA-21385                     9        1     10
TB-21520                    14        6     20
TC-20980                    11        1     12
TS-21370                    12        3     15
ZC-21910                    18       13     31
Total                      460      208    668